@startuml
actor User
participant FrontEnd as FE
participant Bridge as BR
participant DBService as DBS
database Database as DB

User->FE: Do an action
FE->BR: Dispatch an action \n<fire-action>
BR->BR: Authorize the user
alt user authorized case
  BR->DBS: PUT /user/:id: update user score
  DBS->DB: update
  DBS<-DB:
  BR<-DBS: success
  BR->DBS: POST /users
  DBS->DB: query
  DBS<-DB:
  BR<-DBS: return list top 10 users by score
  BR->FE: return list top 10 users by score \n<render-score-board'>
  FE->FE: re-rendering score board
else user not authorized case
  BR->FE: return 403
end

@enduml